apiVersion: v1
kind: Pod
metadata:
  name: hello-container
spec:
  containers:
    - name: hello-container
      image: hello-container
      command: ["echo", "Olá, eu sou o hello-container"]
  restartPolicy: Never
